import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import clientPromise from '../utils/mongodb'
import { useColorMode } from '@chakra-ui/react'
import {useEffect} from 'react'
import NavBar from './components/navbar'

type Props = {
  isConnected:boolean
  userlist?: [{name?:string , text?:string , imgurl?:string}]
}

const Home = ({ isConnected  ,userlist}:Props) => {
  const { colorMode, toggleColorMode } = useColorMode()

  useEffect(()=>{
    if(isConnected && userlist){
      userlist.map(x=>{
        console.log(x.name)
      })
    }
  },[isConnected,userlist])

  return (
    <>
          <NavBar/>
          <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a>Phongs-pal</a>
        </h1>

        <h3 >
         {`You are `}{
            isConnected?'connected':'not connect'
          } to MongoDB 🌐
        </h3>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
          
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by  <code className={styles.code} style={{marginLeft:'10px' ,color:colorMode === 'light' ?'gray':'black'}}>Phongpisut Meemuk 😂 </code>
        </a>
      </footer>
    </div>
    </>
  )
}


export async function getServerSideProps(context:any) {
  try {
    await clientPromise
    // `await clientPromise` will use the default database passed in the MONGODB_URI
    // However you can use another database (e.g. myDatabase) by replacing the `await clientPromise` with the folloing code:
    //
    const client = await clientPromise
    const db = await client.db("db")
    const data = await db.collection('participant').find({}).toArray();
    const userlist = JSON.parse(JSON.stringify(data))
  
    // Then you can execute queries against your database like so:
    // db.find({}) or any of the MongoDB Node Driver commands

    return {
      props: { isConnected: true , userlist },
    }
  } catch (e) {
    console.error(e)
    return {
      props: { isConnected: false },
    }
  }
}

export default Home
